AppLabs/Models/Marketer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketer
    {
        public int Id { get; set; }
        public string EmployerName { get; set; }
        public string MarketerName { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Close { get; set; }
    }
}

AppLabs/Controllers/MarketersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppLabs.Models;

namespace AppLabs.Controllers
{
    [Authorize]
    public class MarketersController : Controller
    {
        private DBContext1 db = new DBContext1();

        // GET: Marketers
        public ActionResult Index()
        {
            return View(db.Marketers.ToList());
        }

        // GET: Marketers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marketer marketer = db.Marketers.Find(id);
            if (marketer == null)
            {
                return HttpNotFound();
            }
            return View(marketer);
        }

        // GET: Marketers/Create
        public ActionResult Create()
        {
            IEnumerable<SelectListItem> items = (from m in db.tblEmployees where m.IsInternalEmployee == false select m).AsEnumerable().Select(m => new SelectListItem  //_context1.Employees.Select(c =>new SelectListItem

            {

                Value = m.FirstName,
                Text = m.FirstName

            });
            // ViewData["items"] = items;

            ViewBag.Sai = items;
            IEnumerable<SelectListItem> items1 = (from m in db.tblEmployees where m.IsInternalEmployee == true select m).AsEnumerable().Select(m => new SelectListItem   //_context1.Employees.Select(c =>new SelectListItem

            {

                Value = m.FirstName,
                Text = m.FirstName

            });

            ViewBag.Name = items1;




            return View();
        }

        // POST: Marketers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save([Bind(Include = "Id,EmployerName,MarketerName,StartDate,Status,Close")] Marketer marketer)
        {
            if (ModelState.IsValid)
            {
                db.Marketers.Add(marketer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(marketer);
        }

        // GET: Marketers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marketer marketer = db.Marketers.Find(id);
            if (marketer == null)
            {
                return HttpNotFound();
            }
            return View(marketer);
        }

        // POST: Marketers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,EmployerName,MarketerName,StartDate,Status,Close")] Marketer marketer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(marketer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(marketer);
        }

        // GET: Marketers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marketer marketer = db.Marketers.Find(id);
            if (marketer == null)
            {
                return HttpNotFound();
            }
            return View(marketer);
        }

        // POST: Marketers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Marketer marketer = db.Marketers.Find(id);
            db.Marketers.Remove(marketer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppLabs/Views/Marketers/Create.cshtml
@model AppLabs.Models.Marketer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Save", "Marketers"))
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(m => m.EmployerName, htmlAttributes: new { @class = "control-label col-md-2" }):

            <div class="col-md-9">
                @Html.DropDownListFor(model => model.EmployerName, new SelectList(ViewBag.Sai, "Value", "Text"), "--Select Employee--", new { @class = "form-control" })

                @*@Html.DropDownList("items", null, "Select Employee", new { @class = "form-control" })*@


                @*@Html.DropDownList("Sai", "Select Employe")*@




                @Html.ValidationMessageFor(c => c.EmployerName, "", new { @class = "text-danger" })

            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(m => m.MarketerName, "Marketer Name", htmlAttributes: new { @class = "control-label col-md-2" }):

            <div class="col-md-9">
                @*@Html.DropDownList("items1", null, "Select Marketer", new { @class = "form-control" })*@
                @*@Html.DropDownList("Name", "Select Marketer")*@
                @Html.DropDownListFor(model => model.MarketerName, new SelectList(ViewBag.Name, "Value", "Text"), "--Select Marketer--", new { @class = "form-control" })

                @Html.ValidationMessageFor(c => c.MarketerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" }):

            <div class="col-md-9">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" }):

            <div class="col-md-9">
                @Html.DropDownListFor(m => m.Status,
                new List<SelectListItem>{
             new SelectListItem { Text = "Open", Value = "Open" },
             new SelectListItem {Text="Closed",Value="Closed"}}, "Select Status", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>





        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppLabs/Views/Marketers/Delete.cshtml
@model AppLabs.Models.Marketer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Marketer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmployerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MarketerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MarketerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Close)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Close)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AppLabs/Views/Marketers/Details.cshtml
@model AppLabs.Models.Marketer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Marketer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmployerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MarketerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MarketerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Close)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Close)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AppLabs/Views/Marketers/Edit.cshtml
@model AppLabs.Models.Marketer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Marketer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.EmployerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MarketerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MarketerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MarketerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Close, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Close, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Close, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppLabs/Views/Marketers/Index.cshtml
@model IEnumerable<AppLabs.Models.Marketer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmployerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MarketerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Close)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EmployerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MarketerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Close)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>